addEventListener("DOMContentLoaded", start);

function start() {
  enableNotesToggle();
  drawAI();
  drawHuman();
}

/**
 * Draws a rectangle that moves around the canvas
 * generated by asking ChatGPT
 * "write a JS program that generates art"
 */
function drawAI() {
  // Set up the canvas
  var canvas = document.getElementById("canvas-ai");
  var ctx = canvas.getContext("2d");

  // Set the dimensions of the canvas
  canvas.width = 500;
  canvas.height = 500;

  // Set some default values for the drawing parameters
  var x = Math.random() * canvas.width;
  var y = Math.random() * canvas.height;
  var hue = 0;
  var directionX = 1;
  var directionY = 1;

  // This function is called repeatedly to create the animated effect
  function draw() {
    // Set the fill color to a random hue
    ctx.fillStyle = "hsl(" + hue + ", 50%, 50%)";

    // Draw a filled rectangle at the current position
    ctx.fillRect(x, y, 10, 10);

    // Update the position of the rectangle for the next frame
    x += directionX;
    y += directionY;

    // If the rectangle has reached the edge of the canvas, reverse its direction
    if (x + 10 > canvas.width || x < 0) {
      directionX *= -1;
    }
    if (y + 10 > canvas.height || y < 0) {
      directionY *= -1;
    }

    // Increment the hue for the next frame
    hue++;
    if (hue >= 360) {
      hue = 0;
    }

    // Request another animation frame
    requestAnimationFrame(draw);
  }

  // Start the animation
  requestAnimationFrame(draw);
}

function enableNotesToggle() {
  const collapseToggle = document.querySelector("#collapse-toggle");
  const collapsible = document.querySelector(".collapsible");

  collapseToggle.addEventListener("click", () => {
    collapsible.classList.toggle("is-not-collapsed");
  });
}

function drawHuman() {
  const canvas = document.getElementById("canvas-human");
  const ctx = canvas.getContext("2d");

  canvas.width = 500;
  canvas.height = 500;

  ctx.fillRect(0, 0, 500, 500);
  const stars = createStars(150);
  twinkle(stars);
}

function createStars(numberOfStars) {
  const canvas = document.getElementById("canvas-human");
  const ctx = canvas.getContext("2d");
  const stars = [];

  for (let i = 0; i < numberOfStars; i++) {
    const x = Math.random() * canvas.width;
    const y = Math.random() * canvas.height;

    // randomise the size of the star between 1 and 4
    const size = Math.random() * 3 + 1;

    const alpha = Math.random();
    const hsl = `hsl(0, 100%, 100%, ${alpha})`;
    ctx.fillStyle = hsl;
    ctx.fillRect(x, y, size, size);
    stars.push({ x, y, size });
  }
  return stars;
}
function twinkle(stars) {
  const canvas = document.getElementById("canvas-human");
  const ctx = canvas.getContext("2d");

  stars.forEach((star) => {
    // randomise rate of twinkle between 1 and 6 seconds
    const interval = Math.random() * 5000 + 1000;

    // twinle each star at its own rate
    setInterval(() => {
      const { x, y, size } = star;

      // colour star black
      ctx.fillStyle = "black";
      // add 1 to size to ensure the black rectangle covers the whole star
      ctx.fillRect(x, y, size + 1, size + 1);

      // then recolour it some random shade of white
      const alpha = Math.random();
      const hsl = `hsl(0, 100%, 100%, ${alpha})`;
      ctx.fillStyle = hsl;
      ctx.fillRect(x, y, size, size);
    }, interval);
  });
}
